repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-builtin-literals
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-symlinks
          - id: check-xml
          - id: check-toml
          - id: check-yaml
            args: [--unsafe]
          - id: debug-statements
          - id: end-of-file-fixer
            exclude: '.*\.sqlite3$'
          - id: fix-byte-order-marker
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-use-type-annotations
          - id: python-no-log-warn
          - id: rst-backticks
